var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/modulos/page.js")
R.c("server/chunks/ssr/_18827253._.js")
R.c("server/chunks/ssr/src_data_curso_ts_294f58d8._.js")
R.c("server/chunks/ssr/_0b727a43._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c1ef9cf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__623640de._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__709fb98b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__58f4c68a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_modulos_page_actions_07b98c4d.js")
R.m(70612)
module.exports=R.m(70612).exports
